% -------------------------------------------------------------------
%  Generated by MATLAB on 4-Dec-2015 13:58:40
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
function myNewFile(fname)


fileName = ['E:\资料\onedrive\code\matlab\冈萨雷斯\',fname,'.m'];
% 判断文件是否存在
if exist(fileName,'file')
    disp('文件已经存在');
else
    str = ['%% ',fname,' Performs ********\n%%\n%%\n'...
        '%% -------------------------------------------------------------------\n'...
        '%%  Copyright 1992-',datestr(clock,'yyyy'),' Ma XiaoLong\n'...
        '%%  $Date: ',datestr(clock,'yyyy/mm/dd HH:MM:SS'),'$\n'...
        '%% -------------------------------------------------------------------\n'];
    fp=fopen(fileName,'w');%'a'表示打开文件a.txt,如果不存在就新建一个
    fprintf(fp,str);
    fclose(fp);
end

